
CREATE TABLE CABECERA_PEDIDO_WEB 
(ID INT PRIMARY KEY IDENTITY(1,1),
CONSECUTIVO VARCHAR(50),
BODEGA VARCHAR(50),
CLIENTE VARCHAR(50),
MONEDA VARCHAR(5),
USUARIO VARCHAR(50),
FECHA_CREACION DATETIME,
USUARIO_MODIFICA VARCHAR(50),
FECHA_MODIFICA DATETIME,
ESTADO VARCHAR(20),
TOTAL_LIBRAS DECIMAL(28,2),
TOTAL_PEDIDO DECIMAL(28,2),
COMPANI VARCHAR (50)
)

CREATE TABLE LINEA_PEDIDO_WEB(
    ID INT PRIMARY KEY IDENTITY(1,1),
	[PEDIDO] [varchar](50) NULL,
	[ARTICULO] [varchar](100) NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[PRECIO] [decimal](28, 2) NULL,
	[CANTIDAD_FACTURAR] [decimal](28, 2) NULL,
	[ESCANEADA] [decimal](28, 2) NULL,
	[LOTE] [varchar](100) NULL,
	[DESCUENTO] [decimal](28, 2) NULL,
	[DESCUENTOPORCENTAJE] [decimal](28, 2) NULL
) 
DROP TABLE LINEA_PEDIDO_WEB

CREATE TABLE CONSECUTIVO_PEDIDO_WEB
(
 ID INT PRIMARY KEY IDENTITY(1,1),
CONSECUTIVO VARCHAR(50)
)

INSERT INTO CONSECUTIVO_PEDIDO_WEB(CONSECUTIVO) VALUES('E-0')

--PROCEDIMIENTO PARA INSERTAR EN CABECERA
CREATE PROCEDURE POS.INSERTAR_PEDIDO_CABECERA
@PEDIDO varchar(50),
@ESTADO varchar(1),
@FECHA_PEDIDO datetime,
@FECHA_PROMETIDA datetime,
@FECHA_PROX_EMBARQU DATETIME,
@EMBARCAR_A varchar(80),
@DIREC_EMBARQUE varchar(8),
@DIRECCION_FACTURA varchar(2000),
@TOTAL_MERCADERIA decimal(28,8),
@MONTO_ANTICIPO INT,
@MONTO_FLETE INT,
@MONTO_SEGURO INT,
@MONTO_DOCUMENTACIO INT,
@TIPO_DESCUENTO1 varchar(1),
@TIPO_DESCUENTO2 varchar(1),
@MONTO_DESCUENTO1 INT,
@MONTO_DESCUENTO2 INT,
@PORC_DESCUENTO1 INT,
@PORC_DESCUENTO2 INT,
@TOTAL_IMPUESTO1 INT,
@TOTAL_IMPUESTO2 INT,
@TOTAL_A_FACTURAR decimal(28,8),
@PORC_COMI_VENDEDOR INT,
@PORC_COMI_COBRADOR INT,
@TOTAL_CANCELADO INT,
@TOTAL_UNIDADES INT,
@IMPRESO varchar(1),
@FECHA_HORA datetime,
@DESCUENTO_VOLUMEN int,
@TIPO_PEDIDO varchar(1),
@MONEDA_PEDIDO varchar(1),
@VERSION_NP INT,
@AUTORIZADO varchar(1),
@DOC_A_GENERAR varchar(1),
@CLASE_PEDIDO varchar(1),
@MONEDA varchar(1),
@NIVEL_PRECIO varchar(12),
@COBRADOR varchar(4),
@RUTA varchar(4),
@USUARIO varchar(25),
@CONDICION_PAGO varchar(4),
@BODEGA varchar(4),
@ZONA varchar(4),
@VENDEDOR varchar(4),
@CLIENTE varchar(20),
@CLIENTE_DIRECCION varchar(20),
@CLIENTE_CORPORAC varchar(20),
@CLIENTE_ORIGEN varchar(20),
@PAIS varchar(4),
@SUBTIPO_DOC_CXC int,
@TIPO_DOC_CXC VARCHAR(4),
@BACKORDER varchar(1), 
@PORC_INTCTE int,
@DESCUENTO_CASCADA varchar(1),
@FIJAR_TIPO_CAMBIO varchar(4),
@ORIGEN_PEDIDO varchar(4),
@CreatedBy varchar(20),
@UpdatedBy varchar(20)
AS
INSERT INTO POS.PEDIDO(
PEDIDO,
ESTADO,
FECHA_PEDIDO,
FECHA_PROMETIDA,
FECHA_PROX_EMBARQU,
EMBARCAR_A,
DIREC_EMBARQUE,
DIRECCION_FACTURA,
TOTAL_MERCADERIA,
MONTO_ANTICIPO,
MONTO_FLETE,
MONTO_SEGURO,
MONTO_DOCUMENTACIO,
TIPO_DESCUENTO1,
TIPO_DESCUENTO2,
MONTO_DESCUENTO1,
MONTO_DESCUENTO2,
PORC_DESCUENTO1,
PORC_DESCUENTO2,
TOTAL_IMPUESTO1,
TOTAL_IMPUESTO2,
TOTAL_A_FACTURAR,
PORC_COMI_VENDEDOR,
PORC_COMI_COBRADOR,
TOTAL_CANCELADO,
TOTAL_UNIDADES,
IMPRESO,
FECHA_HORA,
DESCUENTO_VOLUMEN,
TIPO_PEDIDO,
MONEDA_PEDIDO,
VERSION_NP,
AUTORIZADO,
DOC_A_GENERAR,
CLASE_PEDIDO,
MONEDA,
NIVEL_PRECIO,
COBRADOR,
RUTA,
USUARIO,
CONDICION_PAGO,
BODEGA,
ZONA,
VENDEDOR,
CLIENTE,
CLIENTE_DIRECCION,
CLIENTE_CORPORAC,
CLIENTE_ORIGEN,
PAIS,
SUBTIPO_DOC_CXC,
TIPO_DOC_CXC,
BACKORDER,
PORC_INTCTE,
DESCUENTO_CASCADA,
FIJAR_TIPO_CAMBIO,
ORIGEN_PEDIDO,
CreatedBy,
UpdatedBy
) VALUES
(
@PEDIDO,
@ESTADO,
@FECHA_PEDIDO,
@FECHA_PROMETIDA,
@FECHA_PROX_EMBARQU,
@EMBARCAR_A,
@DIREC_EMBARQUE,
@DIRECCION_FACTURA,
@TOTAL_MERCADERIA,
@MONTO_ANTICIPO,
@MONTO_FLETE,
@MONTO_SEGURO,
@MONTO_DOCUMENTACIO,
@TIPO_DESCUENTO1,
@TIPO_DESCUENTO2,
@MONTO_DESCUENTO1,
@MONTO_DESCUENTO2,
@PORC_DESCUENTO1,
@PORC_DESCUENTO2,
@TOTAL_IMPUESTO1,
@TOTAL_IMPUESTO2,
@TOTAL_A_FACTURAR,
@PORC_COMI_VENDEDOR,
@PORC_COMI_COBRADOR,
@TOTAL_CANCELADO,
@TOTAL_UNIDADES,
@IMPRESO,
@FECHA_HORA,
@DESCUENTO_VOLUMEN,
@TIPO_PEDIDO,
@MONEDA_PEDIDO,
@VERSION_NP,
@AUTORIZADO,
@DOC_A_GENERAR,
@CLASE_PEDIDO,
@MONEDA,
@NIVEL_PRECIO,
@COBRADOR,
@RUTA,
@USUARIO,
@CONDICION_PAGO,
@BODEGA,
@ZONA,
@VENDEDOR,
@CLIENTE,
@CLIENTE_DIRECCION,
@CLIENTE_CORPORAC,
@CLIENTE_ORIGEN,
@PAIS,
@SUBTIPO_DOC_CXC,
@TIPO_DOC_CXC,
@BACKORDER,
@PORC_INTCTE,
@DESCUENTO_CASCADA,
@FIJAR_TIPO_CAMBIO,
@ORIGEN_PEDIDO,
@CreatedBy,
@UpdatedBy
)

--INSERT EN PEDIDO LINEA DE SOFTLAND
create PROCEDURE POS.INSERTAR_PEDIDO_LINEA
(@PEDIDO					VARCHAR(25) 
,@BODEGA					VARCHAR(25) 
,@ARTICULO					VARCHAR(25) 
,@FECHA_ENTREGA				DATETIME
,@PRECIO_UNITARIO			DECIMAL(28, 8)
,@CANTIDAD_PEDIDA			DECIMAL(28, 8)
,@CANTIDAD_A_FACTURA		DECIMAL(28, 8)
,@DESCUENTOMONTO			DECIMAL(28, 8)
,@DESCUENTOPORCENTAJE		DECIMAL(28,8)
,@FECHA_PROMETIDA			DATETIME
,@CreatedBy					VARCHAR(30)
,@UpdatedBy					VARCHAR(30)
) 
AS	
SET NOCOUNT ON
BEGIN
		--DECLARE @MSG VARCHAR(255) 
		--DECLARE @Severity INT 
		--DECLARE @ErrorCode INT
		DECLARE @LINEA INT
		SET @LINEA=CAST( ISNULL((SELECT TOP(1) PEDIDO_LINEA FROM POS.PEDIDO_LINEA WHERE PEDIDO=@PEDIDO ORDER BY PEDIDO_LINEA DESC),0) AS INT)+1
		--BEGIN TRY
				     INSERT INTO POS.[PEDIDO_LINEA]
					   ([PEDIDO]
					   ,[PEDIDO_LINEA]
					   ,[BODEGA]
					   ,[LOTE]
					   ,[ARTICULO]
					   ,[ESTADO]
					   ,[FECHA_ENTREGA]
					   ,[LINEA_USUARIO]
					   ,[PRECIO_UNITARIO]
					   ,[CANTIDAD_PEDIDA]
					   ,[CANTIDAD_A_FACTURA]
					   ,[CANTIDAD_FACTURADA]
					   ,[CANTIDAD_RESERVADA]
					   ,[CANTIDAD_BONIFICAD]
					   ,[CANTIDAD_CANCELADA]
					   ,[TIPO_DESCUENTO]
					   ,[MONTO_DESCUENTO]
					   ,[PORC_DESCUENTO]
					   ,[FECHA_PROMETIDA]
					   ,[RecordDate]
					   ,[CreatedBy]
					   ,[UpdatedBy]
					   ,[CreateDate])
				 VALUES
					   (@PEDIDO
					   ,CAST(@LINEA AS SMALLINT)
					   ,@BODEGA
					   ,NULL
					   ,@ARTICULO
					   ,'N'
					   ,@FECHA_ENTREGA
					   ,0
					   ,@PRECIO_UNITARIO
					   ,@CANTIDAD_PEDIDA
					   ,@CANTIDAD_A_FACTURA
					   ,0
					   ,0
					   ,0
					   ,0
					   ,'P'
					   ,@DESCUENTOMONTO
					   ,@DESCUENTOPORCENTAJE
					   ,@FECHA_PROMETIDA
					   ,GETDATE()
					   ,@CreatedBy
					   ,@UpdatedBy
					   ,GETDATE())			
					 --SELECT SCOPE_IDENTITY() AS IdPedidoLinea
					 --COMMIT TRANSACTION
					SELECT @LINEA PEDIDO_LINEA
		--END TRY
		--BEGIN CATCH
		--			IF @@TRANCOUNT > 0
		--			   ROLLBACK TRANSACTION
       
		--				SET @ErrorCode = Error_Number() 
		--				SET @Severity = Error_Severity() 
		--				SET @MSG = 'An error was thrown: ' 
		--					+ 'Error(' + @ErrorCode + '):' + ERROR_MESSAGE() 
		--					+ ' Severity = ' + ERROR_SEVERITY()  
		--					+ ' State = ' + ERROR_STATE() 
		--					+ ' Procedure = ' + ERROR_PROCEDURE() 
		--					+ ' Line Number = ' + ERROR_LINE()     
		--				RAISERROR(@MSG, @Severity, 2) 
		--END CATCH
END