--CREACION DE MENU
CREATE TABLE [dbo].[MENU_WEB](
	[ID_MENU] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_MENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

--CREACION DE SUBMENU

CREATE TABLE [dbo].[SUBMENU_WEB](
	[ID_SUBMENU] [int] IDENTITY(1,1) NOT NULL,
	[ID_MENU] [int] NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[URL] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_SUBMENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SUBMENU_WEB]  WITH CHECK ADD  CONSTRAINT [FK_SUBMENU_WEB_MENU_WEB] FOREIGN KEY([ID_MENU])
REFERENCES [dbo].[MENU_WEB] ([ID_MENU])
GO

ALTER TABLE [dbo].[SUBMENU_WEB] CHECK CONSTRAINT [FK_SUBMENU_WEB_MENU_WEB]
GO

--CREACION DE ROL
CREATE TABLE [dbo].[ROL_WEB](
	[ID_ROL] [int] IDENTITY(1,1) NOT NULL,
	[ROL] [varchar](50) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ROL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

--CREACION DEL USUARIO WEB
CREATE TABLE [dbo].[USUARIO_WEB](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [varchar](50) NULL,
	[PASS] [varchar](50) NULL,
	[NOMBRE_USUARIO] [varchar](50) NULL,
	[ID_ROL] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[USUARIO_WEB]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_WEB_ROL_WEB] FOREIGN KEY([ID_ROL])
REFERENCES [dbo].[ROL_WEB] ([ID_ROL])
GO

ALTER TABLE [dbo].[USUARIO_WEB] CHECK CONSTRAINT [FK_USUARIO_WEB_ROL_WEB]
GO

--CREACION DE TABLA INTERMEDIA

CREATE TABLE [dbo].[ROL_MENU_WEB](
	[ID_ROL_MENU_WEB] [int] IDENTITY(1,1) NOT NULL,
	[ID_ROL] [int] NULL,
	[ID_MENU] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ROL_MENU_WEB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ROL_MENU_WEB]  WITH CHECK ADD  CONSTRAINT [FK_ROL_MENU_WEB_MENU_WEB] FOREIGN KEY([ID_MENU])
REFERENCES [dbo].[MENU_WEB] ([ID_MENU])
GO

ALTER TABLE [dbo].[ROL_MENU_WEB] CHECK CONSTRAINT [FK_ROL_MENU_WEB_MENU_WEB]
GO

ALTER TABLE [dbo].[ROL_MENU_WEB]  WITH CHECK ADD  CONSTRAINT [FK_ROL_MENU_WEB_ROL_WEB] FOREIGN KEY([ID_ROL])
REFERENCES [dbo].[ROL_WEB] ([ID_ROL])
GO

ALTER TABLE [dbo].[ROL_MENU_WEB] CHECK CONSTRAINT [FK_ROL_MENU_WEB_ROL_WEB]
GO


--Insert de tablas
INSERT INTO MENU_WEB(DESCRIPCION) VALUES('Consulta')
INSERT INTO MENU_WEB(DESCRIPCION) VALUES('Paquete')
INSERT INTO MENU_WEB(DESCRIPCION) VALUES('Pedido')
INSERT INTO MENU_WEB(DESCRIPCION) VALUES('Usuarios')

INSERT INTO SUBMENU_WEB(ID_MENU,URL,DESCRIPCION) VALUES('1','Consultarticulo','Consultar Articulo')
INSERT INTO SUBMENU_WEB(ID_MENU,URL,DESCRIPCION) VALUES('2','CrearPaquete','Crear Paquete')
INSERT INTO SUBMENU_WEB(ID_MENU,URL,DESCRIPCION) VALUES('3','ListarPedido','Lista Pedidos')
INSERT INTO SUBMENU_WEB(ID_MENU,URL,DESCRIPCION) VALUES('3','CrearPedido','Crear Pedido')
INSERT INTO SUBMENU_WEB(ID_MENU,URL,DESCRIPCION) VALUES('4','UserList','Ver Usuarios')
INSERT INTO SUBMENU_WEB(ID_MENU,URL,DESCRIPCION) VALUES('4','RolList','Ver Roles')
INSERT INTO SUBMENU_WEB(ID_MENU,URL,DESCRIPCION) VALUES('4','EdicionMenu','Roles Menu')

INSERT INTO ROL_WEB(ROL,FECHA_CREACION,FECHA_MODIFICACION) VALUES('ADMIN',GETDATE(),GETDATE())
INSERT INTO USUARIO_WEB(USUARIO,PASS,NOMBRE_USUARIO,ID_ROL) VALUES('Admin','123','Administrador',1)

INSERT INTO ROL_MENU_WEB(ID_ROL,ID_MENU) VALUES(1,1)
INSERT INTO ROL_MENU_WEB(ID_ROL,ID_MENU) VALUES(1,2)
INSERT INTO ROL_MENU_WEB(ID_ROL,ID_MENU) VALUES(1,3)
INSERT INTO ROL_MENU_WEB(ID_ROL,ID_MENU) VALUES(1,4)

--CREACION DE TABLA COMPANIA
CREATE TABLE COMPANIWEB
(
ID_COMPANIE INT PRIMARY KEY IDENTITY(1,1),
COMPANIE VARCHAR(20),
CONSECUTIVO_COMPRA VARCHAR(10),
CONSECUTIVO_FISICO VARCHAR(10),
CONSECUTIVO_TRASPASO VARCHAR(10),
CONSECUTIVO_PEDIDO VARCHAR(20)
)